name: temporal-project
concurrency:
  group: temporal-project
  cancel-in-progress: true

on:
  pull_request:
  push:

jobs:
  unit-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Print dir
        run: ls
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'
      - name: Download Go modules
        run: go mod download
      - name: Run unit tests
        run: make test
